version: '2'

services:
      # selfproject:
      #     image: tutum/apache-php
      #     links:
      #         - mysql
      #     ports:
      #         - "8888:80"
      #     networks:
      #         - app-network
      #     volumes:
      #         - .:/var/www/html/selproject
      #     environment:
      #         - ALLOW_OVERRIDE=true
      #     hostname: selfproject
      #     cpu_shares: 512             # 0.5 CPU
      #     mem_limit: 536870912        # 512 MB RAM
      webserver:
        image: nginx
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
          - "8080:80"
        volumes:
          - /nginx:/var/www
        networks:
          - app-network
      mysql:
          image: mysql:5.7
          command: 
            --default-authentication-plugin=mysql_native_password
            --disable-partition-engine-check
          ports:
              - "3309:3306"
          networks:
              - app-network
          volumes:
              - ./mysql-data/:/var/lib/mysql/
          environment:
              - MYSQL_ROOT_PASSWORD=12345
              - MYSQL_DATABASE=selfproject
          hostname: mysql
          restart: unless-stopped
          # cpu_shares: 512             # 0.5 CPU
          # mem_limit: 536870912        # 512 MB RAM
networks:
      app-network: